Use Ruby allocators for `vasprintf`
sparklemotion/nokogiri pull request #2481
Opened 2022-03-19 12:49 UTC by Garfield96

**What problem is this PR intended to solve?**

This is a follow-up PR for #2480, which implements `vasprintf` with Ruby allocators.
Unfortunately, the current implementation results in a segmentation fault. I would highly appreciate it if somebody with more experience with the Ruby API could have a look at this since it looks like it might be a bug in the Ruby implementation of `vsnprintf`.

2022-04-01 18:57 UTC, flavorjones commented
Thank you for submitting this PR! I've kicked off CI ... let's see what the valgrind runs tell us. :crossed_fingers:

2022-04-01 19:33 UTC, flavorjones commented
OK! CI crashes as well, and I can repro in my dev environment. I'm going to take some time to dive in with valgrind and see what I can figure out.

2022-04-01 20:41 UTC, flavorjones commented
OK, so on linux the va_list can't be re-used once va_arg has been called on it. So I've pushed an additional commit to introduce a temporary copy of the va_list for the first call to vsnprintf.

But I think we can actually get rid of vasprintf entirely by simply using `rb_vsprintf` ... going to spike on that now.

2022-04-01 20:43 UTC, stevecheckoway requested changes

2022-04-01 20:43 UTC, stevecheckoway commented on ext/nokogiri/nokogiri.c
> +  char *res = (char *)ruby_xmalloc((unsigned int)len);
`ruby_xmalloc()` returns `void *`, the return values from the `malloc` family of functions should not be cast.

With the previous change above, this line can become
```c
char *rest = ruby_xmalloc(len);
```

2022-04-01 20:43 UTC, stevecheckoway commented on ext/nokogiri/nokogiri.c
> +  int len = vsnprintf(tmp, 1, fmt, tmp_ap) + 1;
The return value for `vsnprintf()` should be checked against `-1`.

```c
int ret = vsnprintf(tmp, 1, fmt, ap);
if (ret == -1)
{
  *strp = NULL;
  return -1;
}
size_t len = ret + 1;
```

2022-04-01 20:43 UTC, stevecheckoway commented on ext/nokogiri/nokogiri.c
>    return vsnprintf(res, (unsigned int)len, fmt, ap);
`len` shouldn't be cast to an `unsigned int`, it's a `size_t`.

2022-04-01 20:43 UTC, stevecheckoway commented on ext/nokogiri/nokogiri.c
>    return vsnprintf(res, (unsigned int)len, fmt, ap);
`va_end` needs to be called before returning the final result.
```c
ret = vsnprintf(res, len, fmt, ap);
va_end(ap);
return ret;
```

2022-04-01 20:47 UTC, stevecheckoway commented
Before running off to teach, I thought I saw a memory leak where a string was allocated via `noko_vasprintf()` but wasn't being freed. The PR changed while I was writing my review and I can't find that any more.

2022-04-01 20:48 UTC, stevecheckoway commented
Also I realized one of my review comments was wrong (about needing to call `ap_end()`; I deleted it).

2022-04-01 20:50 UTC, stevecheckoway commented
@flavorjones Will `rb_vsprintf()` work everywhere? It returns a `VALUE`.

2022-04-01 21:53 UTC, flavorjones commented
@stevecheckoway Thanks for the feedback on this!

I'm about to ship an alternative PR that removes calls to `vasprintf()` entirely, which I think is preferable. I'm going to hold off on making edits to this PR until we can compare the two.

2022-04-01 23:24 UTC, flavorjones commented
See #2489 for an alternative approach

2022-04-02 15:56 UTC, flavorjones commented
Closing in favor of #2489

2022-04-02 15:56 UTC, closed without merging