Serializing unparented HTML node on JRuby
sparklemotion/nokogiri pull request #2895
Opened 2023-05-29 14:30 UTC by cbasguti

**What problem is this PR intended to solve?**

This PR aims to solve issue #2559 in the Nokogiri project. After investigating the reported bug, it was identified that a NullPointerException occurs in the isHtmlScript and isHtmlStyle functions due to the inability to evaluate a null object in Java. The proposed solution involves adding a null check for the getParentNode() method's return value and logging an appropriate message if the parent node is null or does not match the expected tag name. A draft PR will be opened to implement these modifications and gather feedback for effectiveness.

**Have you included adequate test coverage?**

As this is my first contribution to the project, I am uncertain about the appropriate location to include the corresponding test. However, I am committed to ensuring adequate test coverage for this change and will collaborate with the project team to determine the best approach.

**Does this change affect the behavior of either the C or the Java implementations?**

This change only affects the Java implementation, as the issue of a NullPointerException is specific to that platform. The C implementation does not encounter this problem.

2023-05-30 15:16 UTC, flavorjones commented
@cbasguti Thank you for opening this PR! I've kicked off CI, I'd like to see what the test suite says before reviewing.

2023-05-30 16:45 UTC, flavorjones commented
Also, if you didn't see it, I tried to provide some help for initial contributions here: https://nokogiri.org/CONTRIBUTING.html#submitting-pull-requests

Thank you again!

2023-06-02 11:43 UTC, cbasguti commented
Ok, I took another look at the contribution documentation page, included a test following your instructions, and also formatted it as needed. Thank you very much for your patience and I look forward to your comments.

2023-06-02 21:00 UTC, flavorjones commented
Don't worry about the one failing test "ci / bsd", it's flaky. This looks all green, will review over the weekend!

2023-06-03 16:42 UTC, flavorjones requested changes
Looking at how these (private) functions are used, I think the missing abstraction is "isCDATA", which should return true if the parent node name is "script" or "style".

Can you merge these two functions into one, `isCDATA()`? I think you can probably have it return a boolean value something like

```
return htmlDoc && parentNode != null && (parentNode.getNodeName().equals("style") || parentNode.getNodeName().equals("script"))
```

2023-06-03 16:42 UTC, flavorjones commented on ext/java/nokogiri/internals/SaveContextVisitor.java
> +      System.out.println("getParentNode() returned null or parent node is not 'script'.");
We shouldn't emit a message, we should just match the C extension's behavior.

2023-06-03 16:42 UTC, flavorjones commented on ext/java/nokogiri/internals/SaveContextVisitor.java
> +      System.out.println("getParentNode() returned null or parent node is not 'style'.");
We shouldn't emit a message, we should just match the C extension's behavior.

2023-06-05 15:30 UTC, flavorjones commented
Looks good! I think this will go green, and I'll merge it. I've credited you in the CHANGELOG!

Thank you so much for your contribution!

2023-06-05 20:29 UTC, merged

2023-07-05 14:36 UTC, flavorjones commented
Available in [Release 1.15.3 / 2023-07-05 · sparklemotion/nokogiri](https://github.com/sparklemotion/nokogiri/releases/tag/v1.15.3)