extconf: respect AR and RANLIB in recipes on darwin
sparklemotion/nokogiri pull request #3338
Opened 2024-11-15 20:31 UTC by joshheinrichs-shopify

**What problem is this PR intended to solve?**

When using Nix on Darwin, we ideally should be latching onto the Nix-provided AR and RANLIB. Without this, when blocking Xcode via `sandbox-exec`, I see errors like this while attempting to install the gem:
```
xcode-select: note: No developer tools were found, requesting install.
If developer tools are located at a non-default location on disk, use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, and cancel the installation dialog.
See `man xcode-select` for more details.
```

**Have you included adequate test coverage?**

No but this seems relatively harmless?

**Does this change affect the behavior of either the C or the Java implementations?**

No

2024-11-17 19:13 UTC, flavorjones requested changes
Hi @joshheinrichs-shopify, thanks for opening this.

Do you know if there are any github actions that we could use to test Nix-on-Darwin? (For example, we're using `vmactions/freebsd-vm@v1` to test FreeBSD.)

I put in a lot of work over the past few years to thoroughly exercise compilation on supported platforms, and that coverage has allowed me to confidently make changes to `extconf.rb`. I'd prefer not to merge this without adding some test coverage to prevent regressing, if possible.

2024-11-17 19:13 UTC, flavorjones commented on ext/nokogiri/extconf.rb
> +        "RANLIB=#{ENV.fetch("RANLIB", "/usr/bin/ranlib")}",
For libxml2's `configure` script, if an environment variable like `RANLIB` is set, then it doesn't need to be passed explicitly to the configure command. Can you restructure this to something like the following

```ruby
recipe.configure_options << "RANLIB=/usr/bin/ranlib" unless ENV.key?("RANLIB")
recipe.configure_options << "AR=/usr/bin/ar" unless ENV.key?("AR")
```

2024-11-17 19:13 UTC, flavorjones commented on ext/nokogiri/extconf.rb
> +        "RANLIB=#{ENV.fetch("RANLIB", "/usr/bin/ranlib")}",
Same here for libxslt's `configure` script.

2024-11-17 19:14 UTC, flavorjones commented
I'm also curious: can you share why you're not using precompiled gems?

2024-11-26 14:53 UTC, flavorjones approved these changes
Looks good! I kicked off CI.

2024-11-26 14:59 UTC, flavorjones commented on ext/nokogiri/extconf.rb
> +      recipe.configuration_options << "RANLIB=/usr/bin/ranlib" unless ENV.key?("RANLIB")
```suggestion
      recipe.configure_options << "RANLIB=/usr/bin/ranlib" unless ENV.key?("RANLIB")
```

2024-11-26 14:59 UTC, flavorjones commented on ext/nokogiri/extconf.rb
> +      recipe.configuration_options << "RANLIB=/usr/bin/ranlib" unless ENV.key?("RANLIB")
```suggestion
      recipe.configure_options << "RANLIB=/usr/bin/ranlib" unless ENV.key?("RANLIB")
```

2024-11-26 16:32 UTC, joshheinrichs-shopify commented on ext/nokogiri/extconf.rb
> +      recipe.configuration_options << "RANLIB=/usr/bin/ranlib" unless ENV.key?("RANLIB")
🤦 thanks

2024-11-27 18:19 UTC, flavorjones commented
Kicked off CI again.

2024-11-27 18:37 UTC, flavorjones commented
@joshheinrichs-shopify CI is failing. Looks like a tricky one. My guess is that there's inconsistent header usage: `xmlSwitchEncodingName` was added in libxml2 v2.13.0, and so the extconf is checking for its existence using a "modern" libxml2 (maybe Nokogiri's own vendored headers?), but then compiling against something older than that (maybe nix's system headers?). I have no idea what nix package is being linked- and compiled-against so I can't verify that hunch, but something like that is likely the cause.

2024-11-27 18:38 UTC, joshheinrichs-shopify commented
hmm looks like that failing test is latching onto xcode for some reason. taking a look...

2024-11-28 14:00 UTC, flavorjones commented on ext/nokogiri/extconf.rb
> +def unix?
LOL, naming things is hard

2024-11-28 14:05 UTC, flavorjones commented
Just kicked CI and it looks like the darwin-nix-enabled build is green! If everything goes green I'll merge.

2024-11-28 14:26 UTC, merged

2024-11-28 16:28 UTC, flavorjones commented
Thank you! This will be in v1.17.0 when it ships (hopefully very very soon).